# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: 
    
        handler_id: null                # Utiliser le gestionnaire de session par défaut
        cookie_secure: auto             # Transmission du cookie seulement via HTTPS si possible
        cookie_httponly: true           # Accès au cookie seulement via HTTP (pas de JavaScript)
        cookie_samesite: lax            # Politique SameSite (strict, lax, ou none)
        cookie_lifetime: 3600           # Durée de vie du cookie en secondes (1 heure)
        cookie_path: /                  # Chemin pour lequel le cookie est valide
        cookie_domain: null             # Domaine pour lequel le cookie est valide, null pour tout domaine


    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
